// <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarPaintings" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Paintings</a><div class="dropdown-menu" aria-labelledby="navbarPaintings"><a style="background-color: antiquewhite;" class="dropdown-item " href="paintings.html">All Sections</a><a class="dropdown-item" href="#">"Adam and Eve" 2018</a><a class="dropdown-item" href="#">"Color views" 2019</a><a class="dropdown-item" href="#">"Abstract compositions" 2014</a><a class="dropdown-item" href="#">“Linear Heads" 2019</a><a class="dropdown-item" href="#">“City of my dreams" 2012</a><a class="dropdown-item" href="#"> "Digitalization of man"</a><a class="dropdown-item" href="#">"Goddess" 2016</a><a class="dropdown-item" href="#">"Hryhoriy Skovoroda" 2016</a><a class="dropdown-item" href="#">"Impress by Pinsel"</a><a class="dropdown-item" href="#">"Key and nails" 2015</a><a class="dropdown-item" href="#"> "Manipula" 2020</a><a class="dropdown-item" href="#"> "Mathematician" 2018</a><a class="dropdown-item" href="#">"Mystical heads" 2015</a><a class="dropdown-item" href="#">Dutch head" 2019</a><a class="dropdown-item" href="#">"Solomon"s Court" 2016</a><a class="dropdown-item" href="#">"Fighters" 2017</a><a class="dropdown-item" href="#">"Francisk of Assisi" 2015-2017</a><a class="dropdown-item" href="#">"Velo" 2008</a></div></li>
// } 
document.addEventListener("DOMContentLoaded",
    function (event) {
        
        var message = '<header><div class="container"><nav class="navbar navbar-expand-lg navbar-light " style = "background-color: #e3f2fd00;" ><a class="navbar-brand" href="index.html">Pavlo Yarmolyk</a><div class="container-fluid"><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarPaintings" aria-controls="navbarPaintings" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="navbarPaintings"><ul class="navbar-nav ml-auto"><li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarPaintings" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Paintings</a><div class="dropdown-menu" aria-labelledby="navbarPaintings"><a style="background-color: antiquewhite;" class="dropdown-item " href="paintings.html">All Sections</a><a class="dropdown-item" href="#">"Adam and Eve" 2018</a><a class="dropdown-item" href="#">"Color views" 2019</a><a class="dropdown-item" href="#">"Abstract compositions" 2014</a><a class="dropdown-item" href="#">“Linear Heads" 2019</a><a class="dropdown-item" href="#">“City of my dreams" 2012</a><a class="dropdown-item" href="#"> "Digitalization of man"</a><a class="dropdown-item" href="#">"Goddess" 2016</a><a class="dropdown-item" href="#">"Hryhoriy Skovoroda" 2016</a><a class="dropdown-item" href="#">"Impress by Pinsel"</a><a class="dropdown-item" href="#">"Key and nails" 2015</a><a class="dropdown-item" href="#"> "Manipula" 2020</a><a class="dropdown-item" href="#"> "Mathematician" 2018</a><a class="dropdown-item" href="#">"Mystical heads" 2015</a><a class="dropdown-item" href="#">Dutch head" 2019</a><a class="dropdown-item" href="#">"Solomon"s Court" 2016</a><a class="dropdown-item" href="#">"Fighters" 2017</a><a class="dropdown-item" href="#">"Francisk of Assisi" 2015-2017</a><a class="dropdown-item" href="#">"Velo" 2008</a></div></li><li class="nav-item"><a class="nav-link" href="metal.html">Metal Composition </a></li><li class="nav-item"><a class="nav-link" href="#">Mosaic</a></li><li class="nav-item"><a class="nav-link" href="#">Sacral Art</a></li><li class="nav-item"><a class="nav-link" href="#">Wall Painting</a></li></ul ></div ></nav ></div ></div ></header>';
            document.getElementById("content").innerHTML = message;
        }
);
// document.querySelector("button").onclick = sayHello;
